### ISSUE TITLE
How To Do A Static Build

### ISSUE THREAD

**Issue by ProdigyView** [intel/libvpl#110]
I am trying to compile ffmpeg for a static build for distrubiton. When I get this error when I do:

```
 ERROR: libvpl >= 2.6 not found
```
I am currently doing the scripts for installation on linux:

```
if build "oneVPL" "2023.3.1"; then
  # libaom bcfe6fb == v3.5.0
  download "https://github.com/oneapi-src/oneVPL/archive/refs/tags/v2023.3.1.tar.gz" "oneVPL-2023.3.1" "oneVPL"
  cd oneVPL-2023.3.1 || exit
  execute script/bootstrap
  execute script/build
  execute script/install
  build_done "libvpl" "2.3.1"
fi
CONFIGURE_OPTIONS+=("--enable-libvpl")
```

Works fine if I don't do a static build. So can libvpl be compiled for a static compiling of ffmpeg?

**Comment by akwrobel** [comment]
@ProdigyView please check the CMAKE file when compiling VPL, you can set the **BUILD_SHARED_LIBS** to OFF and this should provide the static lib you are looking for.  

If you still have issues can you provide more information on your setup?

**Comment by movy** [comment]
See also https://github.com/intel/cartwheel-ffmpeg/issues/286

**Comment by akwrobel** [comment]
Closed due to age and no further asks from the submitter.
