### ISSUE TITLE
About support for format 444P

### ISSUE THREAD

**Issue by mengker33** [intel/libvpl#114]
We would like to use vpl-backend jpegdec to output 444p format, but there is no 444p fourcc  (i.e. MFX_FOURCC_YUV444) defined in vpl dispatcher (mfxstructures.h). I only see it defined in vpl-gpu-runtime mfxstructures-int.h. Can you add support for 444P?

**Comment by jonrecker** [comment]
Thank you for the input. These enums are also defined separately for the test tools in [sample_utils.h](https://github.com/intel/libvpl/blob/master/tools/legacy/sample_common/include/sample_utils.h#L82) but I agree that these should be defined in a single place in the dispatcher headers, if they are supported by the runtime. We will coordinate with GPU runtime owners on promoting the relevant fourCC's into mfxstructures.h.

**Comment by akwrobel** [comment]
This requires coordination with the VPL GPU Runtime repo, to ensure there aren't multiple conflicting definitions.  An issue can be filed with the VPL GPU RT repo here: https://github.com/intel/vpl-gpu-rt/issues.

**Comment by mengker33** [comment]
Close the ticket for the moment as it needs modification on both vpl dispatch and runtime.
