### ISSUE TITLE
"®" symbol in `pkg-config` file breaking downstream build tools

### ISSUE THREAD

**Issue by elldritch** [intel/libvpl#117]
Hi there! I've been digging into https://github.com/haskell/cabal/issues/9608, which is caused by being unable to parse output from `pkg-config --list-all` when `libvpl` is installed.

This is because a "®" symbol was added to the `Name` and `Description` properties of `vpl.pc` when this project was renamed from "oneVPL" to "libvpl". See the file https://github.com/intel/libvpl/blob/master/libvpl/pkgconfig/vpl.pc.in in commit https://github.com/intel/libvpl/commit/44df6e08cc836ed65725ed344e7ec9ded5193874.

This results in an invalid `pkg-config` file. Note that the `pkg-config` manpages ([link](https://man.archlinux.org/man/core/pkgconf/pc.5.en#PROPERTIES)) define:

> Properties are set using RFC822-style stanzas which consist of a keyword, followed by a colon (:) and then the value the property should be set to.

And [RFC-822](https://www.w3.org/Protocols/rfc822/#:~:text=3.2.%20HEADER%20FIELD%20DEFINITIONS) defines property field bodies to be ASCII characters only, and "®" is not an ASCII character.

Can you please remove this ISO/IEC 8859-1 symbol from the `.pc` output files? Thanks!

**Comment by mav-intel** [comment]
@elldritch Thanks for the report! We will make sure is fixed in the next release!

**Comment by elldritch** [comment]
@mav-intel Thank you! When do you expect the next release to be? This is breaking my builds today, so I am figuring out whether to work around it by temporarily downgrading or whether to temporarily patch it myself.

**Comment by mav-intel** [comment]
Fixed by #121
