### ISSUE TITLE
Messy tagging

### ISSUE THREAD

**Issue by kloczek** [intel/libvpl#123]
Last version seems is `2.10.1` and before that was `2023.4.0`.
Issue is that `2.10.1`  as the version string is not greater than `2023.4.0`.

Q: is that tagging convention change is permanent or accidental? 🤔

**Comment by mav-intel** [comment]
@kloczek The change is intentional. With the product naming/branding change we saw an opportunity to align closer with semantic versioning without confusing customers with a 2023 major version several years down the line.
