### ISSUE TITLE
[Composition] Blur occurs with tiled composition on TGL-U

### ISSUE THREAD

**Issue by james-tang17** [intel/libvpl#126]
Target platform: TGL-U 6305e, i7-1165G7
Target OS: Ubuntu 20.04+ 
libva 2.14.0
media-driver 22.3.1
gmmlib 22.1.2
onevpl_gpu 22.3.2
onevpl 2022.0.3

The target application is NVR, for composition, there are 3 requirements:
- Performance (especially with many input streams such as 64 input streams)
- Scaling quality (AVS algorithm accepted, bi-linear is not good enough)
- Scaling quality consistence

Additionally, there are some rules:
- Due to workload requirements, VDBOX+SFC can’t be used. 
- For best performance in non-full screen composition, tiled composition is used
- To avoid destination Y coordinate alignment caused GPU hang issue on TGL-U GT1, AVS sampler is disabled (EU bi-linear used). https://github.com/intel/media-driver/pull/1499

By disabling VDBOX+SFC and enabling tile composition, we saw blur issue in 2x2 layout composition
![image](https://github.com/intel/libvpl/assets/11536855/61d6fcb0-bb82-4856-8ff8-28903cd1ea45)
![image](https://github.com/intel/libvpl/assets/11536855/7651d3f1-c56e-48bb-82cf-5ac36eccd031)

video #2, video #3 has blur there. 
below is the par file we used to reproduce this issue with sample_multi_transcode
-i::h264 chn_0_video.dat  -join -hw -async 4 -o::sink -vpp_comp_dst_x 0 -vpp_comp_dst_y 0 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25 -vpp_comp_tile_id 0 -i::h265 chn_1_video.dat  -join -hw -async 4  -o::sink -vpp_comp_dst_x 800 -vpp_comp_dst_y 0 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25 -vpp_comp_tile_id 0 -i::h265 chn_1_video.dat  -join -hw -async 4 -o::sink -vpp_comp_dst_x 0 -vpp_comp_dst_y 434 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25 -vpp_comp_tile_id 0 -i::h265 chn_1_video.dat  -join -hw -async 4  -o::sink -vpp_comp_dst_x 800 -vpp_comp_dst_y 434 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25 -vpp_comp_tile_id 0 -vpp_comp_only 4 -vpp_comp_num_tiles 1 -w 1920 -h 1080 -async 4 -threads 2 -join -hw -i::source -ext_allocator -fps 25 -ec::nv12 -rdrm

For all blur case, below is the par file
-i::h264 chn_0_video.dat  -join -hw -async 4 -o::sink -vpp_comp_dst_x 0 -vpp_comp_dst_y 0 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25-i::h265 chn_1_video.dat  -join -hw -async 4 -o::sink -vpp_comp_dst_x 800 -vpp_comp_dst_y 0 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25-i::h265 chn_1_video.dat  -join -hw -async 4 -o::sink -vpp_comp_dst_x 0 -vpp_comp_dst_y 434 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25-i::h265 chn_1_video.dat  -join -hw -async 4 -o::sink -vpp_comp_dst_x 800 -vpp_comp_dst_y 434 -vpp_comp_dst_w 800 -vpp_comp_dst_h 434 -ext_allocator -fps 25-vpp_comp_only 4 -w 1920 -h 1080 -async 4 -threads 2 -join -hw -i::source -ext_allocator -fps 25 -ec::nv12 -rdrm

The question is why there is blur in video #2/#3 when tiled composition enabled.

**Comment by akwrobel** [comment]
@james-tang17 This is not a dispatcher issue, and should be filed against the VPL GPU their repository https://github.com/oneapi-src/oneVPL-intel-gpu

**Comment by james-tang17** [comment]
@akwrobel , thanks for the feedback. will close this issue and submit to the GPU runtime repo.
