### ISSUE TITLE
Missing the real common install location 

### ISSUE THREAD

**Issue by xxzandy** [intel/libvpl#131]
Can build. Although it doesn't do anything residing in under my home. What's the right location and for what files?

**Comment by mav-intel** [comment]
Did you try the steps in the readme under [Using Intel® VPL](https://github.com/intel/libvpl?tab=readme-ov-file#using-intel-vpl) ?

What OS did you build under? What was your CMake installation command line?

**Comment by xxzandy** [comment]
Hi,
Ubuntu 24.04 noble
Linux msrv 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

https://github.com/intel/libvpl readme.md says:
"if you did not install to standard system locations..." giving the impression that install defaults to the right system locations.

https://github.com/intel/libvpl/blob/master/INSTALL.md:
"The following commands will build the project and install it locally in _vplinstall"

So there are no instructions what the normal system location would be. I did as in INSTALL.md:

git clone https://github.com/intel/libvpl
cd libvpl
export VPL_INSTALL_DIR=`pwd`/../_vplinstall
sudo script/bootstrap
cmake -B _build -DCMAKE_INSTALL_PREFIX=$VPL_INSTALL_DIR
cmake --build _build
cmake --install _build

Doesn't matter if I run cmake --install with sudo, it still installs in `pwd`/../_vplinstall

Libva and media-driver-nonfree have install prefix "--libdir=/usr/lib/x86_64-linux-gnu". Should the same be used here?

**Comment by mav-intel** [comment]
Hi @xxzandy,
If you skip providing -DCMAKE_INSTALL_PREFIX it will install to default locations. 
I believe on ubuntu it will install to /usr/local/lib

My understanding is that `/usr/lib/x86_64-linux-gnu` is intended for libraries installed by your distro package manager. while /usr/local is meant for libs that you installed (compiled) yourself.

Having said that there is nothing stopping you from installing anywhere you like. What is important is that the installation location you chose is in the library search path. You can run:
```
cat /etc/ld.so.conf.d/*
```
to see where ld is looking for shared libs, and install in any of those locations

**Comment by akwrobel** [comment]
@xxzandy please let us know if you have other questions related to this topic or this issue will be closed.

**Comment by xxzandy** [comment]
Hi,

Thank you and sorry for not getting back to you immediately. Your suggestion worked (with of course _sudo_ make install). I'm grateful for your help and suggest that you incorporate the info in the general build instructions.

Please go ahead and close the issue.
BR
andy
