### ISSUE TITLE
Calling old mfxInit cause unhandled c++ exception on some platform

### ISSUE THREAD

**Issue by xelement** [intel/libvpl#132]
Let me list a few cases：

case1：
libmfxhw32.dll version 8.18.2.2
driver version 23.20.16.4974
cpu:  Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
model:  ASUSTeK COMPUTER INC.-SKU

case2：
libmfxhw32.dll version 23.02.14.496
libmfx32-gen.dll version 23.03.5.1
driver version 31.00.101.4255
cpu:  x86 12th Gen Intel(R) Core(TM) i5-1240P
model:  LENOVO-LENOVO_MT_82RT

crash stack:
![image](https://github.com/intel/libvpl/assets/3795983/9d478936-5905-4dfc-93f3-31e0cfc54876)

**Comment by akwrobel** [comment]
Closing for now, please re-open if you have new information.
