### ISSUE TITLE
script/test lint error

### ISSUE THREAD

**Issue by xelement** [intel/libvpl#134]
When I run script/test lint，something wrong with：
![image](https://github.com/intel/libvpl/assets/3795983/80db83d1-2854-4985-a65f-79694653a056)

I changed 'origin/main' to 'origin/master', it works fine for me
![image](https://github.com/intel/libvpl/assets/3795983/9a3fc761-045e-40a6-8673-439228e054d5)

**Comment by mav-intel** [comment]
Thanks for submitting the issue! Fixed by changing default branch name to main
