### ISSUE TITLE
decode memory leak

### ISSUE THREAD

**Issue by wangxiaoshuang** [intel/libvpl#135]
I opened 9 H264 rtsp streams with a resolution of 1280 * 720 and decoded them using ffmpeg n6.0.1 h264_qsv after receiving the data. The memory continued to grow higher and higher, increasing by about 1GB in about 3 hours and 300MB in 1 hour. After destroying these resources, the memory did not decrease。

CPU：12th Gen intel(R) Core(TM) i7 12700

**Comment by mav-intel** [comment]
@wangxiaoshuang Could you please share the operating system and setup/command lines you used to help us duplicate the issue?

**Comment by wangxiaoshuang** [comment]
I'm very sorry, I have already resolved it. When I compile ffmpeg, using -- enable-libmfx will cause a memory leak. When I change it to -- enable-libvpl, there will be no memory leak。
