### ISSUE TITLE
Intel Quick Sync HEVC Encoding Labels P Frames as B Frames

### ISSUE THREAD

**Issue by quamt** [intel/libvpl#143]
**Description**
When using Intel Quick Sync to encode HEVC video, P frames are incorrectly labelled as B. 
This behaviour persists across various configurations and significantly impacts the expected frame type structure in the encoded video. 
It appears that Low Delay B-frames (LDB) or Generalized P/B (GPB) frames are used instead of traditional P frames.

**Steps to Reproduce**
Use Intel Quick Sync to encode a video to HEVC format.
Inspect the frame types in the encoded video using tools like "ffprobe".
Observe that P frames are labelled as B frames, even when the encoding configuration is set to produce P frames.
Expected Behavior
P frames should be correctly labelled as P frames in the encoded HEVC video.

**Actual Behavior**
P frames are labelled as B frames, which can cause confusion and potential issues with playback and editing software that relies on correct frame type identification.

**Environment**
CPU: Intel Core i7-1065G7 @ 1.30GHz [TB: 3.49GHz] (4C/8T) <Icelake>
GPU: Intel Iris(R) Plus Graphics (64EU) 300-1100MHz [15W] (31.0.101.2127)
Operating System: Windows 11 x64 (22631) [UTF-8]
Driver Version: 31.0.101.2127
Media SDK: QuickSyncVideo API v1.35

**2nd environment**
CPU Info       13th Gen Intel Core i5-13600 [4.71GHz] (6P+8E,14C/20T) <AlderlakeS>
GPU Info       Intel UHD Graphics 770 (32EU) 300-1550MHz [65W] (31.0.101.5186)
OS             Windows 11 x64 (22631) [UTF-8]
Media SDK      QuickSyncVideo API v2.10

**Additional Information**
This behaviour has been observed consistently across different videos and configurations.
The issue explicitly affects iGPUs. 
The iGPU supports the `NO GPB` setting, but it is not honoured when activated.

**Comment by akwrobel** [comment]
Hi this issue should be filed in https://github.com/intel/vpl-gpu-rt/issues

**Comment by quamt** [comment]
Done. Closing.
Thank you.
