### ISSUE TITLE
Check root privileges

### ISSUE THREAD

**Issue by shazaum** [intel/libvpl#145]
I realized that it is necessary to install some packages, using the bootstrap script.
So I suggest user verification.

**Comment by akwrobel** [comment]
Note your PR is still broken, comments have been left there.

**Comment by shazaum** [comment]
Hi @akwrobel, thanks for reminding me. I'm returning home now, from a city a little far away. As soon as it arrives, I will continue. once again, thank you.

**Comment by tletnes** [comment]
closing due to age
