### ISSUE TITLE
Decoding mpeg2 by OneVPL

### ISSUE THREAD

**Issue by kohshin-tokunaga** [intel/libvpl#148]
Hello,

 

While using OneVPL to decode MPEG2, I encountered an issue. Please see the attached document for details.

 

This issue is very similar to a problem that occurred in the past: 
https://community.intel.com/t5/Media-Intel-Video-Processing/decoding-mpeg2-by-Media-SDK/m-p/1294492

 

Also, I would like to send the project file used for decoding, but the file size is too large to attach to the message. Is there any way to send it?

 

Thank you.

**Comment by kohshin-tokunaga** [comment]
Sorry, this is attached document.
[README.xlsx](https://github.com/user-attachments/files/16093550/README.xlsx)
[mediasdk_system_analyzer_64.txt](https://github.com/user-attachments/files/16093551/mediasdk_system_analyzer_64.txt)

**Comment by tletnes** [comment]
Based on a preliminary review we recommend this be refiled as an issue in the GPU Runtime (https://github.com/intel/vpl-gpu-rt)
