### ISSUE TITLE
Unable to decode h265 video

### ISSUE THREAD

**Issue by GeorgeZaher** [intel/libvpl#149]
Hello,

I have an issue running onevpl and onevpl tools as I always reach a situation that the decode samples in api2ix are enable
to locate the hardware. 

/oneVPL/examples/api2x/hello-decode$ ./a.out -i /home/ron/Desktop/testOneApi/t1/input.h264 
Cannot create session -- no implementations meet selection criter

I humbly request a guide to make this linux code work

Best Regards
George

**Comment by mav-intel** [comment]
>To use Intel® VPL for video processing you need to install at least one
>implementation. Here is a list:
>
>- [Intel® VPL GPU Runtime](https://github.com/intel/vpl-gpu-rt) for use on
 > Intel® Iris® Xe graphics and newer
>- [Intel® Media SDK](https://github.com/Intel-Media-SDK/MediaSDK) for use on
>  legacy Intel® graphics

Did you install an implementation? And if so which one?
You still need the lower level parts of the media/graphics stack. Note that in the vpl-gpu-rt repo it will guide you on installing the lower level components of the graphics stack.

**Comment by GeorgeZaher** [comment]
Hello,
I have MediaSDK and it not working properly as it alwasys looks for hardware, also my intel i5 11th generation should
find it, also compiling interl vpl gpu runtime is not working
 
![image](https://github.com/user-attachments/assets/1aad1351-2c78-45d8-9794-1c2302559f47)

Best Regards
George

**Comment by mav-intel** [comment]
Media SDK implementations do not support API2.x. API1.x examples should work with MediaSDK.  

Have you run vpl-inspect?  What implementations does it see?

**Comment by GeorgeZaher** [comment]
![image](https://github.com/user-attachments/assets/6f97e198-c2aa-44b7-bb44-1945e1c8f76b)

**Comment by mav-intel** [comment]
@GeorgeZaher could you post the output of vpl-inspect?
