### ISSUE TITLE
VPP not work on videoprocess

### ISSUE THREAD

**Issue by 375583810a** [intel/libvpl#150]
I am using a graphics card to convert nv12 to rgb4,
I tested the example hello-vpp， hello-decvpp, they run on the 3d engine，
But I use d3d11vaapi which works on video process

I really hope someone can tell me why this is happening, thanks！
system:window10
graphics card:n100

**Comment by tletnes** [comment]
What command lines are you using? Which work and which fail? It is not clear to us what is going on from these details.
