### ISSUE TITLE
Performance degradation if D3D11 device is reused when calling MFXVideoDECODE_Init/Close

### ISSUE THREAD

**Issue by danielrdt** [intel/libvpl#154]
We encounter an issue with quiet heavy performance degradation in decoder if the underlying Direct3D 11 device is reused while reinitializing the decoder or VPP very often.

To analyze the problem and make it more reproducible independently from our specific solution i modified the example `api1x_core/legacy-decode`. Because the modifications are quiet simple i think i dont need to add my changed code here.

What i have found:
Using the almost unmodified legacy-decode example with some h264 Testdata (60 seconds clip 1920x1080 about ~3500 frames) my Testsystem (Intel i7-1185G7E) decodes it in about 11 seconds (i commented out output to disk to avoid slowdown by disk).
In Windows Task-Manager i could see the GPU is in use by ~30 percent.
So decoding speed is about ~300fps.

Now modify the example to show my problem by adding a loop of about 3000 iterations of `MFXVideoDECODE_Close` and `MFXVideoDECODE_Init` before start decoding:
```
...
// input parameters finished, now initialize decode
sts = MFXVideoDECODE_Init(session, &mfxDecParams);
VERIFY(MFX_ERR_NONE == sts, "Error initializing decode\n");

for (auto i = 0; i < 3000; i++) {
    sts = MFXVideoDECODE_Close(session);
    VERIFY(MFX_ERR_NONE == sts, "Error closing decode\n");

    sts = MFXVideoDECODE_Init(session, &mfxDecParams);
    VERIFY(MFX_ERR_NONE == sts, "Error initializing decode\n");
}

// Query number required surfaces for decoder
MFXVideoDECODE_QueryIOSurf(session, &mfxDecParams, &decRequest);
...
```

After this simple modification (which should not have any impact from my point of view) the same decoding takes about 30 seconds (~100fps). Also the Task-Manager shows GPU utitlization is at ~10%.

So for any reason the Close and (Re-)Initialization degrades the performance quiet significantly.

Additional tests in our software revealed some maybe informative facts:
- It makes no difference if the MFX Session is reused or also reinitialized every time
- Every MFX Session within the same D3D11 Device instance is affected
- The only solution to solve the issue is to create a new D3D11 Device (what is unfortunately no option for us) - after doing so the performance is restored
- I could not see any significant memory raising (leak)
- The degradation is getting worse if the iterations of Init/Close raising
- The GPU utilization sinks while performance getting worse
- It happens with VPL and also via MediaSDK (The Hardware is TGL so both was testable)
- It also happens on different 11th Gen System (Intel i5-1135G7) but not with a very old i3-6300
- If i call `MFXVideoVPP_Init` and `MFXVideoVPP_Close` often instead - the same happens (in our software we have to convert the color format after decode)

Because it behaves differently on different CPU/GPU I'am unsure if it is a VPL/MediaSDK problem at all or an driver issue (used Version 32.0.101.5768 on Windows 10)?

If this is the wrong place for this issue maybe you can point me to the right direction?

Maybe you asking why we reinitialize decoder thousands of times - in our use case we combine multiple different streams on the screen. The streams have different sources with different resolutions. Because the system is running 24/7 over time when the sources changing quiet a lot reinitializations need to be done (so after some days the issue appears in our software).

Do you have any idea how i could solve the problem?

Thank you!

**Comment by mav-intel** [comment]
This is a (recently) known issue. A fix is coming via a new version of the driver. Currently in internal qualification, not sure on release schedule.

**Comment by danielrdt** [comment]
This are great news - thank you!

Because the bug is not within VPL layer we should close the issue here? Or do you want to leave it open till its fixed in the driver?

**Comment by mav-intel** [comment]
I'd like to keep it open here, so that folks that come along and have the same question/concern can see this. Will close when driver release is out.

**Comment by mav-intel** [comment]
Driver with fix went live last Friday - https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
