### ISSUE TITLE
 undefined reference to `__stack_chk_guard' on linking libvpl.so from ffmpeg and libvpl-tools

### ISSUE THREAD

**Issue by akhilxavi** [intel/libvpl#157]
I was trying to compile latest version ffmpeg with libvpl enabled for qsv codecs. When ffmpeg try to link to libvpl.so, I am getting below error,
 
/home/akhil-qsc/qsys/toolchain/bin/../lib/gcc/x86_64-linux-gnu/13.2.0/../../../../x86_64-linux-gnu/bin/ld: /home/akhil-qsc/qsys/x86_64-linux-gnu/install/usr/lib/pkgconfig/..//libvpl.so: undefined reference to `__stack_chk_guard'
collect2: error: ld returned 1 exit status

then fails with
ERROR: libvpl >= 2.6 not found
 
/os$ ls -ll ../x86_64-linux-gnu/install/usr/lib/libvpl*
lrwxrwxrwx 1 root root     11 Sep  9 23:48 ../x86_64-linux-gnu/install/usr/lib/libvpl.so -> libvpl.so.2
lrwxrwxrwx 1 root root     14 Sep  9 23:48 ../x86_64-linux-gnu/install/usr/lib/libvpl.so.2 -> libvpl.so.2.13
-rwxr-xr-x 1 root root 516952 Sep  9 23:48 ../x86_64-linux-gnu/install/usr/lib/libvpl.so.2.13 

I have "CFLAGS="-fno-stack-protector -U_FORTIFY_SOURCE"" enabled in libvpl and ffmpeg make. 
 
why undefined reference to `__stack_chk_guard' happens?

This happens when libvpl-tools try to link to libvpl.so

**Comment by mav-intel** [comment]
Do you still get the same error without specifying -fno-stack-protector?  I suspect that some part of the build is still expecting/building with `-fstack-protector-strong` and this is causing the reference to `__stack_chk_guard`.

**Comment by akhilxavi** [comment]
tried disabling 

if(NOT MINGW)
          #add_compile_options("-fstack-protector-strong")
endif()

in libvpl code that resolved the linking issue.
