### ISSUE TITLE
Where is version 23.3.5 (that supposedly fixed several CVEs)

### ISSUE THREAD

**Issue by coldtobi** [intel/libvpl#166]
Several Intel SAA references a version 23.3.5, for example https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00935.html

However,  I cannot find that version? Any hints would be appreciated :)

**Comment by mav-intel** [comment]
I believe these references refer to builds the driver binary release, which also includes the GPU runtime component of VPL (source code of which is hosted [here](https://github.com/intel/vpl-gpu-rt)).  The for example 23.3.4 is [here](https://github.com/intel/vpl-gpu-rt/releases/tag/intel-onevpl-23.3.4). I would follow up in that repo with questions about specific versions.
