### ISSUE TITLE
Clarification about BUILD_EXPERIMENTAL been enabled by default

### ISSUE THREAD

**Issue by kwizart** [intel/libvpl#168]
In the current version, -DBUILD_EXPERIMENTAL is enabled by default in cmake.

The consequence is that most distributions are likely building with  -DONEVPL_EXPERIMENTAL by default that might have counterproductive consequences...

Can you consider using opt-in for EXPERIMENTAL build or rename it so it's obvious about which particular feature this enable and when it is relevant ?

Thanks in advance.

**Comment by mav-intel** [comment]
Distros have to ship with BUILD_EXPERIMENTAL enabled, or the features will not be available to end users unless they build the runtime and dispatcher themselves. 

Ultimately this is more of a signal to application developers that certain APIs may change in the future, but still give them the option to make hardware features available to their users as soon as possible.

**Comment by kwizart** [comment]
Thanks for the clarifications.
